---
    - name: Install MySQL database
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       login_user: db_root
       login_password: "{{ db_password }}"
       name: "{{ db_name }}"
       state: present

    - name: Create Database user
      mysql_user:
        login_user: db_root
        login_password: "{{ db_password }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
