- name: Deploy a web application
  hosts: web_db_server1, web_db_server2
  become: yes
  tasks:
    - name: Try Ping
      ping:

    - name: Install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python3
        - python-setuptools
        - python-dev-is-python3
        - build-essential
        - python3-pip
        - python3-mysqldb

    - include_tasks: tasks/deploy_db.yml
    - include_tasks: tasks/deploy_web.yml
