---
    - name: Install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python3
        - python-setuptools
        - python-dev-is-python3
        - build-essential
        - python3-pip
        - python3-mysqldb
